name: CI-CD Pipeline

on:
  release:
    types: [created]
  workflow_dispatch:  
   
jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file

    - name: Build with Maven
      env:
        PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }} 
      run: mvn compile jib:build --file pom.xml
  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          
      - name: Azure CLI Action
        uses: Azure/cli@v1.0.7
        with:
          inlineScript: |
            az version
            az config set extension.use_dynamic_install=yes_without_prompt
            az containerapp update -n my-container-app -g rg_cli --image docker.io/tinumistry/empapi:aca000.1    
